## List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:

  - name: backend
    ## working directory as `/ecommerce/backend`
    before: |
      npm install @medusajs/medusa-cli@latest -g
      cd backend
    init: |
      npm install
    command: |
      npm run dev

## List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 9000
    onOpen: ignore
