## List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:

  - name: 1.1. backend
    ## working directory as `/ecommerce/backend`
    before: |
      npm install @medusajs/medusa-cli@latest -g
      cd backend
    init: |
      npm install
    command: |
      npm run dev
      # gp sync-done finished
    openMode: split-left

  - name: 1.2. backend (test)
    ## working directory as `/ecommerce/backend`
    before: |
      cd backend
    init: |
      # echo "curl -X GET localhost:9000/store/products | python -m json.tool"
      echo "npm run seed"
    command: |
      # gp sync-await finished && \
      echo "curl -X GET localhost:9000/store/products | python -m json.tool"
    openMode: split-right

## List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 9000
    onOpen: ignore 