version: "3.8"
services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend:latest
    container_name: ecommerce-backend
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/ecommerce
      REDIS_URL: redis://redis
      NODE_ENV: development
      JWT_SECRET: something
      COOKIE_SECRET: something
      PORT: 9000
    ports:
      - "9000:9000"
    volumes:
      - .:/app/ecommerce
      - backend_node_modules:/app/ecommerce/node_modules

  postgres:
    image: postgres:12.12-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    volumes:
      - postgres_data:/var/lib/postgresql/data/     ## using a volume
      # - ./postgres_data:/var/lib/postgresql/data/   ## if you want to use a bind folder

  redis:
    image: redis:alpine
    container_name: redis
    expose:
      - 6379

volumes:
  backend_node_modules:
  postgres_data: