ports:
  - port: 9999
    onOpen: open-preview

tasks:
  - name: Start Redis Stack
    init: |
     docker-compose pull
    command: |
     alias redis-cli="docker exec -it redis-stack redis-cli" 
     echo "Use redis-cli to interact with Redis here."
     docker-compose up -d
     gp sync-done finished
    openMode: split-left
  - name: Start Express Application
    ## working directory as `/README/lab1.express-redis`
    before: |
      cd README/lab1.express-redis
    init: |
      npm install
    command: |
      gp sync-await finished && \
      npm run dev
    openMode: split-right
